version: '3'

services:
  database:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./lobsters_data:/var/lib/mysql
  lobsters:
    restart: always
    entrypoint: ["/usr/local/bin/docker-entrypoint2.sh"]
    image: chverma/lobsters:latest
    user: "root"
    environment:
      - MARIADB_HOST
      - MARIADB_PORT
      - MARIADB_PASSWORD
      - MARIADB_USER
      - LOBSTER_DATABASE
      - LOBSTER_SITE_NAME
      - RAILS_ENV
      - LOBSTER_HOSTNAME
      - VIRTUAL_HOST
      - RAILS_MAX_THREADS
      - SMTP_PASSWORD
      - SMTP_ADDRESS
      - SMTP_USERNAME
      - SMTP_PORT
      - SECRET_KEY_BASE
    ports:
      - "3000:3000"
    links:
      - database:mariadb
    volumes:
      - ./src/lobsters:/lobsters
      - ./src/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint2.sh
      - ./src/config/database.yml:/lobsters/config/database.yml
      - ./src/config/locales:/lobsters/config/locales
      - ./src/config/secrets.yml:/lobsters/config/secrets.yml
