version: '3'

services:
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lobsters
    ports:
      - "3307:3306"
    volumes:
      - ./lobsters_data:/var/lib/mysql
  lobsters:
    entrypoint: ["/usr/local/bin/docker-entrypoint2.sh"]
    image: chverma/lobsters:latest
    user: "root"
    environment:
      - MARIADB_HOST=database
      - MARIADB_PORT=3306
      - MARIADB_PASSWORD=password
      - MARIADB_USER=root
      - LOBSTER_DATABASE=lobsters
      - LOBSTER_SITE_NAME=APICV News
      - RAILS_ENV=development
      - LOBSTER_HOSTNAME=localhost
      - VIRTUAL_HOST=localhost
      - RAILS_MAX_THREADS=5
    ports:
      - "3000:3000"
    links:
      - database:mariadb
    volumes:
      - ./src/lobsters:/lobsters
      - ./src/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint2.sh
      - ./src/config/database.yml:/lobsters/config/database.yml
      - ./src/config/locales:/lobsters/config/locales
