version: '3'

services:
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lobsters
    ports:
      - "3307:3306"
    volumes:
      - ./lobsters_data:/var/lib/mysql
  lobsters:
    image: utensils/lobsters:latest
    environment:
      - MARIADB_HOST=database
      - MARIADB_PORT=3306
      - MARIADB_PASSWORD=password
      - MARIADB_USER=root
      - LOBSTER_DATABASE=lobsters
      - LOBSTER_SITE_NAME="Example News"
      - RAILS_ENV=development
      - LOBSTER_HOSTNAME=localhost
      - VIRTUAL_HOST=localhost
      - RAILS_MAX_THREADS=5
    ports:
      - "3000:3000"
    links:
      - database:mariadb
volumes:
  lobsters_data:
